### ISSUE TITLE
[Suggestion] Option to put "Hide Member List" inside Collapsible UI Menu?

### ISSUE THREAD

**Issue by SheepCommander** [skullyplugs/collapsible-ui#4]
I just think it would be nice

**Comment by Skullbite** [comment]
Tbh, this does give me the opportunity to give this plugin a code cleanup. I can add it as a setting.

**Comment by Skullbite** [comment]
[Done!](https://github.com/skullyplugs/collapsible-ui)

**Comment by SheepCommander** [comment]
Yay!
